VotingApp/Controllers/TVshowController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VotingApp.Areas.Identity.Data;
using VotingApp.Data;


namespace VotingApp.Controllers
{
    public class TVshowController : Controller
    {
        private readonly AdminDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly UserManager<VoteAppUser> _userManager;
        
        public TVshowController(AdminDbContext context, IWebHostEnvironment hostEnvironment, UserManager<VoteAppUser> userManager)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
            _userManager = userManager;
        }

        // GET: TVshows
        [Authorize]
        public async Task<IActionResult> Index()
        {
            
            return View(await _context.TvShow.ToListAsync());
        }

        // GET: TVshows/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tVshow = await _context.TvShow
                .FirstOrDefaultAsync(m => m.Id == id);
            
            if (tVshow == null)
            {
                return NotFound();
            }

            return View(tVshow);
        }

        // GET: TVshows/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: TVshows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Create([Bind("Id,ShowName,Reviewer,Review,Rating,ImageFile")] TVshow tVshow)
        {
            if (ModelState.IsValid)
            {

                //Reviewer name addition
                
                var userId = _userManager.GetUserId(HttpContext.User);
                VoteAppUser user = _userManager.FindByIdAsync(userId).Result;
                tVshow.Reviewer = user.Name;
                

                //image addition
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(tVshow.ImageFile.FileName);
                string extention = Path.GetExtension(tVshow.ImageFile.FileName);
                tVshow.ShowImg=fileName = fileName + DateTime.Now.ToString("yymmssffff") + extention;
                string path = Path.Combine(wwwRootPath + "/Image/", fileName);
                using (var fileStream=new FileStream(path, FileMode.Create))
                {
                    await tVshow.ImageFile.CopyToAsync(fileStream);
                }

                _context.Add(tVshow);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tVshow);
        }
        
        // GET: TVshows/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tVshow = await _context.TvShow.FindAsync(id);
            //var show = (TVshow)_context.TvShow.Where(j => j.Id == id).FirstOrDefault();
            //var current = tVshow.Reviewer;
            if (tVshow == null)
            {
                return NotFound();
            }
            return View(tVshow);
        }

        // POST: TVshows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ShowName,Reviewer,Review,Rating,ShowImg")] TVshow tVshow)
        {
            if (id != tVshow.Id)
            {
                return NotFound();
            }
            //var show = _context.TvShow.FirstOrDefaultAsync(m => m.Id == id);

            string current = tVshow.Reviewer;
            var userId = _userManager.GetUserId(HttpContext.User);
            VoteAppUser user = _userManager.FindByIdAsync(userId).Result;
            tVshow.Reviewer = user.Name;
           



            if (ModelState.IsValid)
                {
                    try
                    {
                      if (user.Name==current)
                      {
                       _context.Update(tVshow);
                      }
                         await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!TVshowExists(tVshow.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(tVshow);
            //}
            //else
            //{
            //    return NotFound();
            //}
        }
        [Authorize]
        // GET: TVshows/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tVshow = await _context.TvShow
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tVshow == null)
            {
                return NotFound();
            }
           

            return View(tVshow);
        }

        // POST: TVshows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tVshow = await _context.TvShow.FindAsync(id);

            string current = tVshow.Reviewer;
            var userId = _userManager.GetUserId(HttpContext.User);
            VoteAppUser user = _userManager.FindByIdAsync(userId).Result;
            if (user.Name == current)
            {
                var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "image", tVshow.ShowImg);
                if (System.IO.File.Exists(imagePath))
                    System.IO.File.Delete(imagePath);
                _context.TvShow.Remove(tVshow);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TVshowExists(int id)
        {
            return _context.TvShow.Any(e => e.Id == id);
        }
    }
}

VotingApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using VotingApp.Areas.Identity.Data

@inject SignInManager<VoteAppUser> SignInManager
@inject UserManager<VoteAppUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - The Reviews</title>

    <link rel="stylesheet" href="~/Styles/Style.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/siteS.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jq-3.6.0/dt-1.12.1/b-2.2.3/fc-4.1.0/sc-2.0.7/sb-1.3.4/sp-2.0.2/sl-1.4.0/datatables.min.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body class="bg">




    <header>
        <nav class="navbar navbar-dark navbar-expand-lg navbar-toggleable-lg bg-dark box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">The Reviews</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="TVshow" asp-action="Index">TV Shows</a>
                            </li>
                             <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="TVshow" asp-action="Create">Add TV Show Reviews</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Tvshow">TV Shows</a>
                            </li>
                        }
                        @*<li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="AdminUser" asp-action="Vote">Proceed to Vote</a>
                            </li>*@
                       
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div id="total" class="container divob">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="footer text-white-50">
        <div class="container">
            &copy; 2022 - The Reviews (By Shaqiq) - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-3.6.0/dt-1.12.1/b-2.2.3/fc-4.1.0/sc-2.0.7/sb-1.3.4/sp-2.0.2/sl-1.4.0/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>

</html>